// The committed reference brain (public/brains) is a valid version 2 snapshot with positions.
// Regenerated by extract (spec 004, quickstart step 2); its body must match the 003 brain.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseSnapshot } from '../public/js/brain/snapshot.js';

const REFERENCE = fileURLToPath(new URL('../public/brains/smallest-functional-brain.brain', import.meta.url));

function loadReference() {
  const b = readFileSync(REFERENCE);
  return parseSnapshot(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

test('reference brain has 11 neurons and 78 edges', () => {
  const snap = loadReference();
  assert.equal(snap.neuronCount, 11);
  assert.equal(snap.edgeCount, 78);
});

test('every reference neuron has a soma of three integers', () => {
  const { manifest } = loadReference();
  for (const neuron of manifest.neurons) {
    assert.ok(Array.isArray(neuron.soma), `neuron ${neuron.index} has no soma`);
    assert.equal(neuron.soma.length, 3);
    for (const v of neuron.soma) assert.ok(Number.isInteger(v), `neuron ${neuron.index} soma is not integer`);
  }
});

test('reference brain names its position source', () => {
  const { manifest } = loadReference();
  assert.equal(
    manifest.provenance.positionSource,
    'body-annotations-male-cns-v1.0-minconf-0.5.feather:somaLocation',
  );
});
